# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0968ead4-f53d-4c4a-87e2-7b23c3d7dd8d'
  imageRepository: 'nginx19'
  containerRegistry: 'zscaler.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: CopyFiles@2
      inputs:
       targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: |
        Contents: |
          defination.yaml
          service.yaml
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
 
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        manifests: |
           $(Build.ArtifactStagingDirectory)/defination.yaml
           $(Build.ArtifactStagingDirectory)/service.yaml
        kubernetesServiceConnection: 'test'
        containers: |
            zscaler.azurecr.io/nginx19:57

